### ISSUE TITLE
CAN'T RUN

### ISSUE THREAD

**Issue by xingyu1210** [Sedicmetrix/btd6cefarm#1]
Can you help record a usage video? After running mapidentifier.py and switching back to the game, there was no response. I don't know how to use your script file.

**Comment by Sedicmetrix** [comment]
This might be lack of permissions, running mapidentifier.py in your terminal as admin/superuser may solve the issue.

Windows:
python C:\path\to\mapidentifier.py

Linux/MacOS:
sudo python3 /path/to/mapidentifier.py

I can make a video if this doesn’t work though :)

**Comment by xingyu1210** [comment]
> 这可能是由于缺少权限，以管理员/超级用户身份在终端中运行 mapidentifier.py 可能会解决该问题。
> 
> Windows： python C:\path\to\mapidentifier.py
> 
> Linux/MacOS： sudo python3 /path/to/mapidentifier.py
> 
> 如果这不管用的话我可以录制视频 :)

**Comment by xingyu1210** [comment]
I don't know what counts as running correctly (not familiar with Python). I have some questions. Firstly, is the resolution of 1280 * 720 for window mode or full screen gaming? Secondly, when I use PyCharm to open a PyCharm file, does the game need to enter the map or the map selection interface or the lobby interface when the script runs. I hope to record a teaching session. Thank you very much.

**Comment by Sedicmetrix** [comment]
The resolution 1280x720 is for fullscreen. As for the game, you want to have entered the map that has bonus rewards. I recorded a video of setting the whole thing up as per my machine. On windows it should be very similar just with the different commands.

https://youtu.be/LCRXgMsUz0o

I hope this helps. :)

**Comment by xingyu1210** [comment]
> 分辨率 1280x720 适用于全屏。至于游戏，您需要进入有奖励的地图。我录制了一个视频，按照我的机器设置整个过程。在 Windows 上，它应该非常相似，只是命令不同。
> 
> https://youtu.be/LCRXgMsUz0o
> 
> 我希望这会有所帮助。:)

thank you so much!
